version: '3.7'

services:
  webapi-net6:
    container_name: api-frontend
    restart: always
    build:
      context: .
      dockerfile: src/WebAPI.Frontend/Dockerfile
    ports:
      - 80:5001
    networks:
      - lan-network

networks:
  lan-network:
    external:
      name: docker-net
